version: "3"
services:
  web: 
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    expose: 
      - "1433"
    environment:
      SA_PASSWORD: "DunkleKonigreich!0678"
      ACCEPT_EULA: "Y"