version: "3"
services:
  proxy:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
  web: 
    build: .
    expose:
      - "80"
    depends_on:
      - db
      - proxy
    restart: always
  db:
    image: "microsoft/mssql-server-linux"
    expose: 
      - "1433"
    environment:
      SA_PASSWORD: "DunkleKonigreich!0678"
      ACCEPT_EULA: "Y"