version: "3"
services:
  web: 
    image: todoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "DunkleKonigreich!0678"
      ACCEPT_EULA: "Y"